### ISSUE TITLE
Customize navButtons

### ISSUE THREAD

**Issue by workteam123** [Learus/react-material-ui-carousel#33] opened 2020-07-08 08:10 UTC
Thanks for the carousel - is there a way to customize the nav buttons and bottom buttons? I know it takes a className prop but I cant get this to style the buttons.

**Comment by Learus** [comment] 2020-07-08 09:05
Hello there!
As of now, there is no way to customize the nav buttons or the indicator buttons. I might add a way to do that in the future, but feel free to add if you would like and if you have the time for it.

**Comment by gakin95** [comment] 2020-09-26 22:39
navButtonsAlwaysVisible={true} is not showing the navButton
. i'm i doing something wrong?

**Comment by Learus** [comment] 2020-09-27 11:57
@gakin95
I've recreated your problem as a [new issue](https://github.com/Learus/react-material-ui-carousel/issues/58). Please don't post irrelevant questions in already existing issues.

**Comment by Learus** [comment] 2020-10-28 18:10
Duplicate of #60.

**Closed by Learus** 2020-10-28 18:10 UTC
Labels: enhancement
