### ISSUE TITLE
Gap between slides

### ISSUE THREAD

**Issue by ylihao** [Learus/react-material-ui-carousel#66] opened 2020-10-15 05:17 UTC
Hi thank you for the great work!

I have one question, when using a slide-in animation, is it possible for the next page to slide in immediately after the current page that is sliding out? Right now what I see in the demo, the current page has to slide completely out of the viewport only the next page will slide in, leaving a moment of blank gap between the transition.

Thank you!

**Comment by Learus** [comment] 2020-10-15 05:46
Duplicate of #20

**Closed** 2020-10-15 05:46 UTC
Labels: duplicate
