### ISSUE TITLE
 findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by talhawaqar** [Learus/react-material-ui-carousel#121] opened 2021-10-07 08:19 UTC
# Carousel showed this warning

```

index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:217461:30)
    at Fade (http://localhost:3000/static/js/vendors~main.chunk.js:24888:24)
    at div
    at CarouselItem (http://localhost:3000/static/js/vendors~main.chunk.js:211333:56)
    at div
    at Carousel (http://localhost:3000/static/js/vendors~main.chunk.js:211045:5)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:30326:31)
    at Slider (http://localhost:3000/static/js/main.chunk.js:1445:3)
    at div
    at div
    at Profile (http://localhost:3000/static/js/main.chunk.js:2445:81)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:215042:29)
    at PrivateRoute (http://localhost:3000/static/js/main.chunk.js:228:14)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:215244:29)
    at div
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:214673:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:214196:35)
    at App (http://localhost:3000/static/js/main.chunk.js:255:83)
    at StylesProvider (http://localhost:3000/static/js/vendors~main.chunk.js:28841:24)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:211488:20)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2526
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
findHostInstanceWithWarning @ react-dom.development.js:25406
findDOMNode @ react-dom.development.js:26067
performEnter @ Transition.js:245
updateStatus @ Transition.js:228
componentDidMount @ Transition.js:172
commitLifeCycles @ react-dom.development.js:20663
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
loadImages @ Profile.tsx:119
async function (async)
loadImages @ Profile.tsx:103
(anonymous) @ Profile.tsx:122
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157

```

# Code
## Slider
```
import Carousel from 'react-material-ui-carousel';
import Item from './SliderItem';

import './Slider.css';

const chunkArray = (myArray, chunkSize) => {
  let index = 0;
  const arrayLength = myArray.length;
  const tempArray = [];

  for (index = 0; index < arrayLength; index += chunkSize) {
    const myChunk = myArray.slice(index, index + chunkSize);
    tempArray.push(myChunk);
  }
  return tempArray;
};

export default function Slider({ items, status, onImageClick }) {
  const displayItems = () => {
    const chunk = chunkArray(items, 3);
    return chunk.map((arr) => (
      <div key={arr} className="item-container">
        {arr.map((item) => (
          <Item key={item.path} item={item} status={status} onClick={onImageClick} />
        ))}
      </div>
    ));
  };

  return <Carousel autoPlay={false}>{displayItems()}</Carousel>;
}

````

## Item

```
export default function SliderItem({ status, item, onClick }) {
  return (
    <img
      alt="Generated"
      className={status === 'pending' ? 'slider-image img-pending' : 'slider-image'}
      onClick={() => onClick(item)}
      src={item.path}
    />
  );
}
```

**Comment by bradrice** [comment] 2021-10-11 13:33
I'm wondering the same.

**Comment by andrejordi** [comment] 2021-10-17 04:45
I'm same warning.
```
<Carousel navButtonsAlwaysVisible indicators={false}>
  {
     data.map( (item,i) => 
         <CardMedia
               key={i}
               component="img"
               height="250"
               image={item.ruta}
               alt={item.alt}
         />)
  }
</Carousel>
                
```

**Comment by Learus** [comment] 2021-10-30 12:22
Duplicate of #32

**Closed by Learus** 2021-10-30 12:22 UTC
