### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode.

### ISSUE THREAD

**Issue by HarryF514** [Learus/react-material-ui-carousel#102] opened 2021-06-17 02:47 UTC
Just let you know, I am getting this with your example. 

`<Carousel>
        {product?.gfImages.map((image, i) => (
          <Item key={image.id} item={image} />
        ))}
      </Carousel>`

`function Item(props) {
  return (
    <Paper>
      <img src={props.item.src}></img>
    </Paper>
  );
}`

**Comment by Learus** [comment] 2021-07-05 19:05
Duplicate of #32

**Closed by Learus** 2021-07-05 19:05 UTC
